# name属性用来指定这个工作流的名字
name: Download The SUBSCRIBE

on:
  push:
    branches:
      - main
  schedule:   
    - cron:  5 */4 * * *   #国际标准时间，北京时间+8，即下午1点钟；8:00~23:00， 每4小时运行


jobs:
  run-csjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
      - name: Download the subscribe
        run: |
          sh ./run.sh
      - name: Commit Changes
        run: |
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
         git add .
         git commit -m"由github actions推送,日期:`date`"
         git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
